# Generated by Django 4.2.6 on 2023-10-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_coupontype_participanttype_participant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='in_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
